baseURL = "http://nonocast.cn/"
languageCode = "en-us"
title = "nonocast"
theme = "hugo-kiera"
publishdir = "public"
pygmentsCodeFences = true

[markup.goldmark.renderer]
    unsafe = true

[author]
    name = "nonocast"
    github = "nonocast"
    twitter = "@nonocast"
